"""profile core：Profile 根、证据、事实表与修订

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-21 22:12:37.307832

对应 `docs/data-model.md` 的迁移顺序 1：`personal_profiles`、`profile_evidences`、
六张事实表（skills/experiences/projects/educations/languages/preferences）与 `profile_revisions`。

数据真实性约束由数据库强制而不是只靠应用层：
- `profile_skills` 的 `claim_status = 'VERIFIED'` 必须挂有 `source_evidence_id`，否则无凭据的陈述
  无法被标成"已验证事实"。
- 所有事实表通过 `RESTRICT` 外键持有证据，证据与其支撑的事实不会互相"消失"。
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级到本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_profiles',
    sa.Column('singleton_key', sa.String(length=32), server_default=sa.text("'default'"), nullable=False, comment='固定为 default；唯一约束保证 V1 只有一份主档案。'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='姓名。'),
    sa.Column('headline', sa.String(length=200), nullable=True, comment='一句话头衔，例如 Backend Engineer。'),
    sa.Column('summary', sa.Text(), nullable=True, comment='个人简介。'),
    sa.Column('email', sa.String(length=320), nullable=True, comment='联系方式；仅存于本地库，日志与 AI 提示词不得无条件输出。'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='联系方式；仅存于本地库，日志与 AI 提示词不得无条件输出。'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='所在城市。'),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='公开链接列表，元素形如 {label, url}；不参与比较，因此使用 JSONB。'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.CheckConstraint("singleton_key = 'default'", name=op.f('ck_personal_profiles_singleton_key_fixed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_profiles')),
    sa.UniqueConstraint('singleton_key', name='uq_personal_profiles_singleton_key')
    )
    op.create_table('profile_evidences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL_DECLARATION', 'RESUME_DOCUMENT', 'WORK_PROOF', 'PROJECT_LINK', 'CERTIFICATE', 'OTHER', name='source_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='证据标题，例如证书名称。'),
    sa.Column('content', sa.Text(), nullable=True, comment='证据内容或说明。'),
    sa.Column('source_url', sa.String(length=2048), nullable=True, comment='可核验的外部链接。'),
    sa.Column('source_hash', sa.String(length=128), nullable=True, comment='来源内容哈希，用于识别同一份证据的重复导入。'),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'UNVERIFIED', 'UNCERTAIN', name='verification_status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'UNVERIFIED'"), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='归档时间；非空表示该证据已从界面移除但保留引用完整性。'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], name=op.f('fk_profile_evidences_profile_id_personal_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_evidences'))
    )
    op.create_index(op.f('ix_profile_evidences_profile_id'), 'profile_evidences', ['profile_id'], unique=False)
    op.create_table('profile_preferences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('job_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='职位类型，例如 FULL_TIME、CONTRACT。'),
    sa.Column('salary_min', sa.Integer(), nullable=True, comment='期望薪资下限，按月计。'),
    sa.Column('salary_max', sa.Integer(), nullable=True, comment='期望薪资上限，按月计。'),
    sa.Column('salary_currency', sa.String(length=3), nullable=True, comment='ISO 4217 币种代码。'),
    sa.Column('remote_preference', sa.Enum('ANY', 'ONSITE', 'HYBRID', 'REMOTE', name='remote_preference', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='排除条件，例如不接受的行业或公司。'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_max >= salary_min', name=op.f('ck_profile_preferences_salary_range_ordered')),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], name=op.f('fk_profile_preferences_profile_id_personal_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_preferences')),
    sa.UniqueConstraint('profile_id', name='uq_profile_preferences_profile_id')
    )
    op.create_index(op.f('ix_profile_preferences_profile_id'), 'profile_preferences', ['profile_id'], unique=False)
    op.create_table('profile_revisions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False, comment='同一档案内自增，从 1 开始。'),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='当时的事实内容与来源证据 ID；匹配与简历只能引用它，不能直接读当前事实表。'),
    sa.Column('reason', sa.String(length=200), nullable=False, comment='创建原因，例如 生成投递简历。'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.CheckConstraint('revision_no > 0', name=op.f('ck_profile_revisions_revision_no_positive')),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], name=op.f('fk_profile_revisions_profile_id_personal_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_revisions')),
    sa.UniqueConstraint('profile_id', 'revision_no', name='uq_profile_revisions_profile_id_revision_no')
    )
    op.create_index(op.f('ix_profile_revisions_profile_id'), 'profile_revisions', ['profile_id'], unique=False)
    op.create_table('profile_educations',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('school', sa.String(length=200), nullable=False),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('degree', sa.String(length=64), nullable=True, comment='学位或学历层次。'),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_evidence_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR end_date >= start_date', name=op.f('ck_profile_educations_end_after_start')),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], name=op.f('fk_profile_educations_profile_id_personal_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['profile_evidences.id'], name=op.f('fk_profile_educations_source_evidence_id_profile_evidences'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_educations'))
    )
    op.create_index(op.f('ix_profile_educations_profile_id'), 'profile_educations', ['profile_id'], unique=False)
    op.create_table('profile_experiences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='职位名称。'),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True, comment='为空表示当前仍在职。'),
    sa.Column('responsibilities', sa.Text(), nullable=True, comment='职责描述。'),
    sa.Column('achievements', sa.Text(), nullable=True, comment='成果描述，鼓励量化。'),
    sa.Column('source_evidence_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_profile_experiences_end_after_start')),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], name=op.f('fk_profile_experiences_profile_id_personal_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['profile_evidences.id'], name=op.f('fk_profile_experiences_source_evidence_id_profile_evidences'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_experiences'))
    )
    op.create_index(op.f('ix_profile_experiences_profile_id'), 'profile_experiences', ['profile_id'], unique=False)
    op.create_table('profile_languages',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=True, comment='水平描述，例如 CET-6、雅思 7.0。'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_evidence_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], name=op.f('fk_profile_languages_profile_id_personal_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['profile_evidences.id'], name=op.f('fk_profile_languages_source_evidence_id_profile_evidences'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_languages'))
    )
    op.create_index(op.f('ix_profile_languages_profile_id'), 'profile_languages', ['profile_id'], unique=False)
    op.create_table('profile_projects',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True, comment='本人角色。'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='技术栈列表；V1 无需跨用户统计，因此用 JSONB 而非关联表。'),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_evidence_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR end_date >= start_date', name=op.f('ck_profile_projects_end_after_start')),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], name=op.f('fk_profile_projects_profile_id_personal_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['profile_evidences.id'], name=op.f('fk_profile_projects_source_evidence_id_profile_evidences'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_projects'))
    )
    op.create_index(op.f('ix_profile_projects_profile_id'), 'profile_projects', ['profile_id'], unique=False)
    op.create_table('profile_skills',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='技能原名，保留用户书写。'),
    sa.Column('name_normalized', sa.String(length=100), nullable=False, comment='规范化技能名（小写、折叠空白），用于同一档案内的唯一约束。'),
    sa.Column('category', sa.String(length=64), nullable=True, comment='技能分类，例如语言、框架、工具。'),
    sa.Column('proficiency', sa.Enum('BASIC', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiency', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=True, comment='使用年限，可含小数。'),
    sa.Column('source_evidence_id', sa.UUID(), nullable=True, comment='支撑该技能的来源证据。'),
    sa.Column('claim_status', sa.Enum('VERIFIED', 'UNVERIFIED', 'UNCERTAIN', name='claim_status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'UNVERIFIED'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.CheckConstraint("claim_status <> 'VERIFIED' OR source_evidence_id IS NOT NULL", name=op.f('ck_profile_skills_verified_requires_evidence')),
    sa.CheckConstraint('years_of_experience IS NULL OR years_of_experience >= 0', name=op.f('ck_profile_skills_years_non_negative')),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], name=op.f('fk_profile_skills_profile_id_personal_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['profile_evidences.id'], name=op.f('fk_profile_skills_source_evidence_id_profile_evidences'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_skills')),
    sa.UniqueConstraint('profile_id', 'name_normalized', name='uq_profile_skills_profile_id_name_normalized')
    )
    op.create_index(op.f('ix_profile_skills_profile_id'), 'profile_skills', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_skills_profile_id'), table_name='profile_skills')
    op.drop_table('profile_skills')
    op.drop_index(op.f('ix_profile_projects_profile_id'), table_name='profile_projects')
    op.drop_table('profile_projects')
    op.drop_index(op.f('ix_profile_languages_profile_id'), table_name='profile_languages')
    op.drop_table('profile_languages')
    op.drop_index(op.f('ix_profile_experiences_profile_id'), table_name='profile_experiences')
    op.drop_table('profile_experiences')
    op.drop_index(op.f('ix_profile_educations_profile_id'), table_name='profile_educations')
    op.drop_table('profile_educations')
    op.drop_index(op.f('ix_profile_revisions_profile_id'), table_name='profile_revisions')
    op.drop_table('profile_revisions')
    op.drop_index(op.f('ix_profile_preferences_profile_id'), table_name='profile_preferences')
    op.drop_table('profile_preferences')
    op.drop_index(op.f('ix_profile_evidences_profile_id'), table_name='profile_evidences')
    op.drop_table('profile_evidences')
    op.drop_table('personal_profiles')
    # ### end Alembic commands ###
