"""resume core：简历方向、不可变版本、证据关联与候选稿

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-21 22:35:45.228741

对应 `docs/data-model.md` 的迁移顺序 2：`resumes`、`resume_versions`、
`resume_version_evidences` 与 `resume_drafts`。

"不可变"与"确认才生效"由结构保证，而不是靠调用方自觉：
- `resume_versions` 没有 `updated_at` 与 `version` 列，因此在数据模型层面就无法表达"更新版本"，
  历史投递引用的版本不会被任何后续编辑改写。
- `resume_drafts` 的 `confirmed_status_matches_version` 要求"状态为已确认"与"存在确认产出的版本"
  同时成立或同时不成立，避免状态与产出自相矛盾的记录。
- `failed_requires_code` 要求失败候选稿必须带安全错误码，防止"生成失败"表现为一份来源不明、
  却看起来可用的内容。
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级到本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('name', sa.String(length=200), nullable=False, comment='简历方向名称，例如 Java 后端。'),
    sa.Column('target_direction', sa.String(length=200), nullable=True, comment='目标方向，用于区分同一档案下的多份简历，例如 后端 / AI 应用。'),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False, comment='同一简历内自增，从 1 开始。'),
    sa.Column('profile_revision_id', sa.UUID(), nullable=False, comment='生成该版本时使用的资料修订；保证简历可复现，而不是指向会继续变化的当前事实。'),
    sa.Column('document_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='结构化的简历文档；条目可携带 source_fact_id 指回 Profile 事实，用于校验未编造内容。'),
    sa.Column('render_schema_version', sa.Integer(), nullable=False, comment='document_json 的结构版本，决定用哪套渲染与解析规则解释它。'),
    sa.Column('created_reason', sa.String(length=200), nullable=False, comment='创建原因，例如 首次创建 / 针对某职位定制 / 确认候选稿。'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.CheckConstraint('render_schema_version > 0', name=op.f('ck_resume_versions_render_schema_version_positive')),
    sa.CheckConstraint('version_no > 0', name=op.f('ck_resume_versions_version_no_positive')),
    sa.ForeignKeyConstraint(['profile_revision_id'], ['profile_revisions.id'], name=op.f('fk_resume_versions_profile_revision_id_profile_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_versions_resume_id_resumes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_versions')),
    sa.UniqueConstraint('resume_id', 'version_no', name='uq_resume_versions_resume_id_version_no')
    )
    op.create_index(op.f('ix_resume_versions_profile_revision_id'), 'resume_versions', ['profile_revision_id'], unique=False)
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('resume_drafts',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('base_resume_version_id', sa.UUID(), nullable=True, comment='作为改写基线的版本；为空表示这是一份从零生成的候选稿。'),
    sa.Column('document_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='候选内容；确认前不进入任何正式版本。'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'DISCARDED', 'FAILED', name='status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('confirmed_resume_version_id', sa.UUID(), nullable=True, comment='确认后产出的版本；唯一约束保证一个版本只由一次确认产生。'),
    sa.Column('generator_name', sa.String(length=64), server_default=sa.text("'MANUAL'"), nullable=False, comment='生成方标识；手工构造为 MANUAL，接入模型后写入模型名。'),
    sa.Column('generator_version', sa.String(length=64), nullable=True, comment='生成方版本，用于区分同一生成方的不同输出。'),
    sa.Column('failure_code', sa.String(length=64), nullable=True, comment='失败时的安全错误码；不保存上游原始错误文本。'),
    sa.Column('failure_message', sa.Text(), nullable=True, comment='面向用户的失败说明，不得包含堆栈或密钥。'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.CheckConstraint("(status = 'CONFIRMED') = (confirmed_resume_version_id IS NOT NULL)", name=op.f('ck_resume_drafts_confirmed_status_matches_version')),
    sa.CheckConstraint("status <> 'FAILED' OR failure_code IS NOT NULL", name=op.f('ck_resume_drafts_failed_requires_code')),
    sa.ForeignKeyConstraint(['base_resume_version_id'], ['resume_versions.id'], name=op.f('fk_resume_drafts_base_resume_version_id_resume_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['confirmed_resume_version_id'], ['resume_versions.id'], name=op.f('fk_resume_drafts_confirmed_resume_version_id_resume_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_drafts_resume_id_resumes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_drafts')),
    sa.UniqueConstraint('confirmed_resume_version_id', name='uq_resume_drafts_confirmed_resume_version_id')
    )
    op.create_index(op.f('ix_resume_drafts_resume_id'), 'resume_drafts', ['resume_id'], unique=False)
    op.create_table('resume_version_evidences',
    sa.Column('resume_version_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.ForeignKeyConstraint(['evidence_id'], ['profile_evidences.id'], name=op.f('fk_resume_version_evidences_evidence_id_profile_evidences'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_resume_version_evidences_resume_version_id_resume_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_version_evidences')),
    sa.UniqueConstraint('resume_version_id', 'evidence_id', name='uq_resume_version_evidences_resume_version_id_evidence_id')
    )
    op.create_index(op.f('ix_resume_version_evidences_evidence_id'), 'resume_version_evidences', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_resume_version_evidences_resume_version_id'), 'resume_version_evidences', ['resume_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_version_evidences_resume_version_id'), table_name='resume_version_evidences')
    op.drop_index(op.f('ix_resume_version_evidences_evidence_id'), table_name='resume_version_evidences')
    op.drop_table('resume_version_evidences')
    op.drop_index(op.f('ix_resume_drafts_resume_id'), table_name='resume_drafts')
    op.drop_table('resume_drafts')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_profile_revision_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_table('resumes')
    # ### end Alembic commands ###
