"""申请记录与不可变状态事件

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-22 19:02:34.339445
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级到本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('job_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('job_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('resume_version_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.Enum('SAVED', 'PREPARING', 'READY_TO_APPLY', 'APPLIED', 'CONTACTED', 'INTERVIEWING', 'OFFERED', 'REJECTED', 'WITHDRAWN', 'CLOSED', name='application_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.ForeignKeyConstraint(['job_opportunity_id'], ['job_opportunities.id'], name=op.f('fk_applications_job_opportunity_id_job_opportunities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_snapshot_id'], ['job_snapshots.id'], name=op.f('fk_applications_job_snapshot_id_job_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_applications_resume_version_id_resume_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('job_opportunity_id', 'attempt_no', name=op.f('uq_applications_job_opportunity_id'))
    )
    op.create_index(op.f('ix_applications_job_opportunity_id'), 'applications', ['job_opportunity_id'], unique=False)
    op.create_index(op.f('ix_applications_job_snapshot_id'), 'applications', ['job_snapshot_id'], unique=False)
    op.create_index(op.f('ix_applications_resume_version_id'), 'applications', ['resume_version_id'], unique=False)
    op.create_table('application_events',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.Enum('SAVED', 'PREPARING', 'READY_TO_APPLY', 'APPLIED', 'CONTACTED', 'INTERVIEWING', 'OFFERED', 'REJECTED', 'WITHDRAWN', 'CLOSED', name='from_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('SAVED', 'PREPARING', 'READY_TO_APPLY', 'APPLIED', 'CONTACTED', 'INTERVIEWING', 'OFFERED', 'REJECTED', 'WITHDRAWN', 'CLOSED', name='to_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_events_application_id_applications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_events')),
    sa.UniqueConstraint('application_id', 'sequence_no', name=op.f('uq_application_events_application_id'))
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_applications_resume_version_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_snapshot_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_opportunity_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
