"""版本化匹配报告

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-22 19:10:48.242682
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级到本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_results',
    sa.Column('job_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('profile_revision_id', sa.UUID(), nullable=False),
    sa.Column('resume_version_id', sa.UUID(), nullable=True),
    sa.Column('match_kind', sa.String(length=16), nullable=False),
    sa.Column('engine_name', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.ForeignKeyConstraint(['job_snapshot_id'], ['job_snapshots.id'], name=op.f('fk_match_results_job_snapshot_id_job_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_revision_id'], ['profile_revisions.id'], name=op.f('fk_match_results_profile_revision_id_profile_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_match_results_resume_version_id_resume_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_results'))
    )
    op.create_index(op.f('ix_match_results_job_snapshot_id'), 'match_results', ['job_snapshot_id'], unique=False)
    op.create_index(op.f('ix_match_results_profile_revision_id'), 'match_results', ['profile_revision_id'], unique=False)
    op.create_index(op.f('ix_match_results_resume_version_id'), 'match_results', ['resume_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_results_resume_version_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_profile_revision_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_job_snapshot_id'), table_name='match_results')
    op.drop_table('match_results')
    # ### end Alembic commands ###
