"""ai model configuration：服务商与模型配置

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 00:00:00.000000

对应 [ADR 0004](docs/adr/0004-ai-model-configuration.md)：单人用户可维护多个 OpenAI
兼容服务商与模型，并选择唯一默认模型。

关键约束由数据库强制而不是只靠应用层：
- `uq_ai_models_provider_id_remote_model_id`：同一服务商下远端模型标识不可重复。
- `uq_ai_models_default` 是**部分唯一索引**，只约束 `is_default` 为真的行，
  从而在数据库层保证"至多一个默认模型"，而不依赖服务层事务的并发正确性。
- `ai_models.provider_id` 使用 `CASCADE`：删除服务商即清理其模型配置；
  服务层仍会在删除前检查默认模型，避免静默绕过"默认模型必须存在"的约束。
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级到本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('name', sa.String(length=100), nullable=False, comment='服务商显示名称；唯一。'),
    sa.Column('base_url', sa.String(length=2048), nullable=False, comment='OpenAI 兼容接口基地址；仅允许 HTTPS 或本地回环 HTTP。'),
    sa.Column('api_key_ciphertext', sa.Text(), nullable=True, comment='API Key 的可逆密文；明文不落库，密文不返回客户端。'),
    sa.Column('api_key_mask', sa.String(length=32), nullable=True, comment='仅供界面展示的末四位掩码；不含可用于调用的信息。'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='可选说明，仅用于用户记忆用途。'),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='停用后其模型不得作为默认模型，也不能被连接测试使用。'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers')),
    sa.UniqueConstraint('name', name='uq_ai_providers_name')
    )
    op.create_table('ai_models',
    sa.Column('provider_id', sa.UUID(), nullable=False, comment='所属服务商；服务商删除时级联清理其模型配置。'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型显示名称，供用户识别用途。'),
    sa.Column('remote_model_id', sa.String(length=200), nullable=False, comment='发送给兼容接口的模型标识，同一服务商内唯一。'),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='停用后不再参与默认模型候选。'),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='唯一默认启用标记；由部分唯一索引保证至多一行为真。'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC），由 ORM 在更新时刷新。'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观锁版本号；每次更新自增，接口提交旧值即返回 409。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）。'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_models_provider_id_ai_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models')),
    sa.UniqueConstraint('provider_id', 'remote_model_id', name='uq_ai_models_provider_id_remote_model_id')
    )
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_index('uq_ai_models_default', 'ai_models', ['is_default'], unique=True, postgresql_where=sa.text('is_default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退本修订。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ai_models_default', table_name='ai_models', postgresql_where=sa.text('is_default'))
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
